## D01 作業

In [22]:
import numpy as np

### 1.生成一個等差數列，首數為0，尾數為20，公差為1的數列。

In [26]:
np.arange(0,21,1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

### 2.呈上題，將以上數列取出偶數。

In [24]:
np.arange(0,21,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

### 3.呈1題，將數列取出3的倍數。

In [27]:
np.arange(0,21,3)

array([ 0,  3,  6,  9, 12, 15, 18])

### 4. [簡答題] 請問下列兩種將 Array 轉換成 List 的方式有何不同？

```
print('list(a): ', list(a))
print('tolist(): ', a.tolist())
```


In [18]:
print('list(a) 只會把第一層的元素轉換成 List，多層的話只有第一層會轉；')
print('tolist() 才能達成多層的型態轉換。')


list(a) 只會把第一層的元素轉換成 List，多層的話只有第一層會轉；
tolist() 才能達成多層的型態轉換。


### 5. 請試著在程式中印出以下三個 NdArray 的屬性並且解釋結果？（屬性：ndim、shape、size、dtype、itemsize、length、type）

```
a = np.random.randint(10, size=6) 
b = np.random.randint(10, size=(3,4)) 
c = np.random.randint(10, size=(2,3,2)) 
```

In [4]:
# 記得先 Import 正確的套件

import random
import numpy as np

In [40]:

a = np.random.randint(10, size=6) 
print(a)
print('ndim:', a.ndim) ##多少維度
print('shape:', a.shape) ## 每個維度的大小
print('size:', a.size) ## 陣列中有幾個元素
print('dtype:', a.dtype) ## 陣列中的資料型態
print('itemsize:', a.itemsize) ## 陣列中每個元素所佔用的空間
print('data:',a.data) ## 陣列所存在的記憶體位置
print('length:',len(a))#顯示最外層元素總數
print('type:',type(a))#顯示矩陣的資料型態

[2 3 0 4 8 9]
ndim: 1
shape: (6,)
size: 6
dtype: int64
itemsize: 8
data: <memory at 0x7fb4265b5940>
length: 6
type: <class 'numpy.ndarray'>


In [41]:
b = np.random.randint(10, size=(3,4)) 
print(b)
print('ndim:', b.ndim)
print('shape:', b.shape)
print('size:', b.size)
print('dtype:', b.dtype)
print('itemsize:', b.itemsize)
print('data',b.data)
print('length:',len(b))
print('type:',type(b))

[[6 8 3 2]
 [0 9 7 5]
 [3 4 4 7]]
ndim: 2
shape: (3, 4)
size: 12
dtype: int64
itemsize: 8
data <memory at 0x7fb4279ef210>
length: 3
type: <class 'numpy.ndarray'>


In [42]:
c = np.random.randint(10, size=(2,3,2)) 
print(c)
print('ndim:', c.ndim)
print('shape:', c.shape)
print('size:', c.size)
print('dtype:', c.dtype)
print('itemsize:', c.itemsize)
print('data',c.data)
print('length:',len(c))
print('type:',type(c))

[[[1 6]
  [5 8]
  [3 1]]

 [[5 3]
  [3 5]
  [5 4]]]
ndim: 3
shape: (2, 3, 2)
size: 12
dtype: int64
itemsize: 8
data <memory at 0x7fb427d0f450>
length: 2
type: <class 'numpy.ndarray'>


### 6. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


In [91]:
a = np.random.randint(10, size=6) 

print(a.tolist())
print(list(a))


[0, 3, 7, 7, 2, 2]
[0, 3, 7, 7, 2, 2]


In [92]:
b = np.random.randint(10, size=(3,4)) 

print(b.tolist())
print(list(b))


[[9, 1, 6, 2], [6, 1, 3, 6], [0, 2, 3, 1]]
[array([9, 1, 6, 2]), array([6, 1, 3, 6]), array([0, 2, 3, 1])]


In [93]:
c = np.random.randint(10, size=(2,3,2)) 

print(c.tolist())
print(list(c))


[[[1, 0], [5, 6], [1, 0]], [[2, 0], [0, 6], [0, 8]]]
[array([[1, 0],
       [5, 6],
       [1, 0]]), array([[2, 0],
       [0, 6],
       [0, 8]])]


In [97]:
def tolist(iterable):
    k = []
    n = len(iterable)
    if n > 2:
        for i in range(n):
            k.append(list(iterable)[i].tolist())
        return k
    else:
        return iterable

        
print(tolist(a))
print(tolist(b))
print(tolist(c))

[0, 3, 7, 7, 2, 2]
[[9, 1, 6, 2], [6, 1, 3, 6], [0, 2, 3, 1]]
[[[1 0]
  [5 6]
  [1 0]]

 [[2 0]
  [0 6]
  [0 8]]]
