## D03 作業

In [2]:
import numpy as np

### 1. [簡答題] 請比較 np.zeros 和 np.empty 產生出來的陣列有何差異？為什麼要設計兩種方法？

```
print(np.zeros((2, 3)))
print(np.empty((2, 3)))
```


In [4]:
print(np.zeros((2, 3)))
print('依照傳入的形狀引數，建立元素全為 0、全為 1 的陣列。')
print(np.empty((2, 3)))
print('不需要給定起始值，但是可以建立給定形狀的陣列，元素值則會隨機給定。')

[[0. 0. 0.]
 [0. 0. 0.]]
依照傳入的形狀引數，建立元素全為 0、全為 1 的陣列。
[[0. 0. 0.]
 [0. 0. 0.]]
不需要給定起始值，但是可以建立給定形狀的陣列，元素值則會隨機給定。


In [32]:
'''
np.zeros((2, 3)) 會產生真正的 0；np.empty((2, 3)) 會產生一個近似於 0 的陣列。
np.empty 可以用於只是想要初始化，但之後就會數值覆寫過的形況。
'''

'\nnp.zeros((2, 3)) 會產生真正的 0；np.empty((2, 3)) 會產生一個近似於 0 的陣列。\nnp.empty 可以用於只是想要初始化，但之後就會數值覆寫過的形況。\n'

### 2. 在不用「整數亂數方法」的限制下，如何將包含小數的轉換整數？請將給定的 a 陣列當中的元素變成去掉小數變成整數。


In [5]:
# 記得先 Import 正確的套件
import random

In [23]:
# 轉換前
a = np.random.rand(2, 3)
a

array([[0.88129708, 0.07707256, 0.6149063 ],
       [0.53358887, 0.03932002, 0.96814621]])

In [24]:
# 轉換後
a= np.array(a, dtype = int)
a

array([[0, 0, 0],
       [0, 0, 0]])

In [30]:
# standard ans
print(a.round())
print(np.round(a))

[[0 0 0]
 [0 0 0]]
[[0 0 0]
 [0 0 0]]


### 3. 承上題，怎樣可以限制整數的範圍介於 m - n 之間？請將給定的 a 陣列當中的元素的範圍調整成 m - n 之間。


In [28]:
m = 20
n = 40

np.reshape(np.linspace(m,n,6),(2,3))

array([[20., 24., 28.],
       [32., 36., 40.]])

In [31]:
#standard answer
a = np.random.rand(2, 3) * (n - m)
b = a
print(a)
print(b)
print( b % 1) # a(b) 的小數部分
#故: a-b%1 會轉為整數
print((a - b % 1) + m)

[[19.92983255  8.13430931  7.51549696]
 [ 7.43325351  8.04988055  6.42664509]]
[[19.92983255  8.13430931  7.51549696]
 [ 7.43325351  8.04988055  6.42664509]]
[[0.92983255 0.13430931 0.51549696]
 [0.43325351 0.04988055 0.42664509]]
[[39. 28. 27.]
 [27. 28. 26.]]
