## D04 作業 

### 1. [簡答題] 請問下列程式碼，運算結果分別為何？

```
a = np.array( [20,30,40,50] )
b = np.array( [1,2,3,4] ) 
c = 1
d = np.array( [1] )
e = np.array( [1,2] ) 
```


In [3]:
import numpy as np

a = np.array([20,30,40,50])
b = np.array([1,2,3,4]) 
c = 1
d = np.array([1])
e = np.array([1,2]) 

print(a + a)
print(a + b)
print(a + c)
print(a + d)
print(a + e)

[ 40  60  80 100]
[21 32 43 54]
[21 31 41 51]
[21 31 41 51]


ValueError: operands could not be broadcast together with shapes (4,) (2,) 

### 2. 如何在不用迴圈的情況下計算 (A+B)*(-A/2) ？那用迴圈怎麼做？


In [8]:
## 不用迴圈

A = np.ones(3)*1
B = np.ones(3)*2

(A+B)*(-A/2)

array([-1.5, -1.5, -1.5])

In [13]:
## 用迴圈

A = np.ones(3)*1
B = np.ones(3)*2

arr = []
for i in range(len(A)):
    temp = B[i]+A[i]
    temp1 = -(A[i])/2
    arr.append(temp*temp1)
arr

[-1.5, -1.5, -1.5]

### 3. 請問如何計算「1x6 的單位矩陣」和「6x1 的單位矩陣」的內積和外積？


In [26]:
A = np.ones((1,6))
B = np.ones((6,1))

## 點積
print("點積：",np.dot(A,B))

## 內積
print("內積：",np.inner(A.T,B))

##外積
print("外積：",np.outer(A,B))

點積： [[6.]]
內積： [[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]
外積： [[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [28]:
## 參考解答
print(A * B)
print(A @ B)

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]
[[6.]]


## 延伸題

作業目標:<br>
嘗試練習log的函式並應用<br>
作業重點:<br>
學員需要複習log的轉換方式<br>
熟悉運用指數函數以及對數函數

題目:<br>
運用投影片中的分貝公式回答下列問題。

### 1.正常的談話的聲壓為20000微巴斯卡，請問多少分貝?

In [37]:
## dB = 20 log (量到的聲壓/參考聲壓 (人類最小聽到的:20 μPa ))

V1 = 20000
V0 = 20

20*np.log10(V1/V0)  # log10底數為10，log底數為e

60.0

### 2. 30分貝的聲壓會是50分貝的幾倍?

In [43]:
#2.30分貝的聲壓會是50分貝的幾倍?

dB = 30
V1 = 10**1.5*np.log10(20) ## np.log10(V1)= 1.95
V1

41.14218090497171

In [44]:
dB = 50
V2 = 10**2.5*np.log10(20)
V2

411.4218090497172

In [45]:
V1/V2

0.09999999999999998