## D05

### 1. 產生一個 1-11 的一維陣列，並且把 3-6 由正數變成負數。



In [2]:
import numpy as np

In [3]:
arr = np.arange(11)+1
for i in arr:
    if i>=3 and i <= 6:
        arr[i] = -arr[i]
print(arr)

[ 1  2  3 -4  5 -6  7  8  9 10 11]


In [4]:
##解答
Z = np.arange(11)+1

Z[(3 <= Z) & (Z < 7)] *= -1
print(Z)

[ 1  2 -3 -4 -5 -6  7  8  9 10 11]


### 2. 試著從一個隨機陣列中，找出比 0.5 大的數有幾個？



In [6]:
A = np.random.rand(3, 6)
print(A)
print(A>0.5)
print(np.sum(A>0.5))  ## True = 1

[[0.49796442 0.69695902 0.52646306 0.52596593 0.86080071 0.12156971]
 [0.30659117 0.28772477 0.05460492 0.57595137 0.75940715 0.6307173 ]
 [0.80117408 0.50902006 0.0531966  0.5617312  0.25656502 0.21165966]]
[[False  True  True  True  True False]
 [False False False  True  True  True]
 [ True  True False  True False False]]
10


In [7]:
## 解答
print(A[A > 0.5].size)

10


作業目標<br>
計算有缺失值的資料，統計量實作<br>
作業重點<br>
當遇到缺失值有函式可以處理，不須額外寫程式刪除<br>
計算統計量時不能出現缺失值

題目:<br>
english_score = np.array([55,89,76,65,48,70])<br>
math_score = np.array([60,85,60,68,np.nan,60])<br>
chinese_score = np.array([65,90,82,72,66,77])<br>
上3列共六位同學的英文、數學、國文成績，第一個元素代表第一位同學，舉例第一位同學英文55分、數學60分、國文65分，今天第五位同學因某原因沒來考試，導致數學成績缺值，運用上列數據回答下列問題。

In [13]:
english_score = np.array([55,89,76,65,48,70])
math_score = np.array([60,85,60,68,np.nan,60])
chinese_score = np.array([65,90,82,72,66,77])

### 1. 請計算各科成績平均、最大值、最小值、標準差，其中數學缺一筆資料可忽略?

In [19]:
# 英文
print("英文科")
print("平均：", np.mean(english_score))
print("最大值：", np.max(english_score))
print("最小值：", np.min(english_score))
print("標準差：", np.std(english_score))

英文科
平均： 67.16666666666667
最大值： 89
最小值： 48
標準差： 13.433995020924426


In [26]:
# 數學 - 缺一筆
print("數學科")
print("平均：", np.mean(math_score))
print("最大值：", np.max(math_score))
print("最小值：", np.min(math_score))
print("標準差：", np.std(math_score))

print("\n")
np.isnan(math_score)
print("平均：", np.mean(math_score[~np.isnan(math_score)])) ##空值不列入計算
print("最大值：", np.max(math_score[~np.isnan(math_score)]))
print("最小值：", np.min(math_score[~np.isnan(math_score)]))
print("標準差：", np.std(math_score[~np.isnan(math_score)]))

數學科
平均： nan
最大值： nan
最小值： nan
標準差： nan


平均： 66.6
最大值： 85.0
最小值： 60.0
標準差： 9.707728879609279


In [27]:
# 國文
print("國文科")
print("平均：", np.mean(chinese_score))
print("最大值：", np.max(chinese_score))
print("最小值：", np.min(chinese_score))
print("標準差：", np.std(chinese_score))

國文科
平均： 75.33333333333333
最大值： 90
最小值： 65
標準差： 8.825468196582484


### 2. 第五位同學補考數學後成績為55，請計算補考後數學成績平均、最大值、最小值、標準差?

In [37]:
fill_value = 55
math_score = np.array([60,85,60,68,np.nan,60])
math_score[np.isnan(math_score)] = fill_value  ## 不可使用 math_score[math_score == np.nan] = fill_value
print(math_score)
print("平均：", np.mean(math_score))
print("最大值：", np.max(math_score))
print("最小值：", np.min(math_score))
print("標準差：", np.std(math_score))

[60. 85. 60. 68. 55. 60.]
平均： 64.66666666666667
最大值： 85.0
最小值： 55.0
標準差： 9.860132971832694


### 3. 用補考後資料找出與國文成績相關係數最高的學科?

In [43]:
# math vs chinese
np.corrcoef(math_score, chinese_score)[0,1]

0.740568027023363

In [42]:
# english vs chinese
np.corrcoef(english_score, chinese_score)[0,1]

0.9779282830211268

In [44]:
print("英文與國文的相關係數較高")

英文與國文的相關係數較高
