## D06

### 1. [簡答題] 請問下列這三種方法有什麼不同？

```
print(a.sum()) 
print(np.sum(a))
print(sum(a)) 
```



In [1]:
'''
sum() 是 python 內建的函式，所有型態皆可以用。np.sum(a) 跟 a.sum() 是陣列專有的函式，差別在於定義在 np 或是 array 底下。
'''

'\nsum() 是 python 內建的函式，所有型態皆可以用。np.sum(a) 跟 a.sum() 是陣列專有的函式，差別在於定義在 np 或是 array 底下。\n'

### 2. 請對一個 5x5 的隨機矩陣作正規化的操作。


In [2]:
# 記得先 Import 正確的套件
import numpy as np

In [3]:
A = np.random.random((5, 5))
A = (A - A.min()) / (A.max() - A.min())
A

array([[0.21855216, 0.41468771, 0.51743715, 0.94711372, 0.70672012],
       [0.55916011, 0.92137741, 0.59674356, 0.03567704, 0.        ],
       [0.66030303, 0.04229682, 0.92579908, 0.1529171 , 0.56170884],
       [0.04190845, 1.        , 0.75506547, 0.06958934, 0.34585786],
       [0.00438623, 0.78754908, 0.02432158, 0.9975368 , 0.63228671]])

### 3. 請建立一個長度等於 10 的正整數向量，並且將其中的最大值改成 -1。


In [8]:
Z = np.random.random(10)
Z.max()

0.9972109198500131

In [9]:
Z.argmax()  ## 找出最大值位於第幾個數

4

In [13]:
Z[Z.argmax()] = -1

In [14]:
Z

array([ 0.83119395,  0.20300459,  0.2252511 ,  0.84552212, -1.        ,
        0.17372717,  0.64729217,  0.75163841,  0.18528069,  0.8622363 ])

作業目標<br>
熟悉陣列維度轉換，並且會擷取需要資料<br>
作業重點<br>
使用reshap須注意order用法<br>
where可以運用邏輯條件擷取資料

### 1.將下列清單(list1)，轉成維度為(5X6)的array，順序按列填充。(hint:order="F")

In [17]:
arr = np.arange(30).reshape(5,6,order='F')
arr

array([[ 0,  5, 10, 15, 20, 25],
       [ 1,  6, 11, 16, 21, 26],
       [ 2,  7, 12, 17, 22, 27],
       [ 3,  8, 13, 18, 23, 28],
       [ 4,  9, 14, 19, 24, 29]])

### 2.呈上題的array，找出被6除餘1的數的索引

In [19]:
np.where(arr%6==1)

(array([0, 1, 2, 3, 4]), array([5, 0, 1, 2, 3]))