## D07

#### [作業目標]

1. 請比較對一個 100 x 100 * 100 的陣列，使用不同方法對每一個元素 +1 的時間比較。

2. 如何從一個陣列中，找出出現頻率最高的數值與位置？

3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


### 1. 請比較對一個 1000 x 100 x 100 的陣列，使用不同方法對每一個元素 +1 的時間比較。




In [1]:
import numpy as np

In [8]:
## 多為陣列的多為迴圈
Z = np.random.randint(0, 10, 1000000).reshape(100, 100, 100)

In [4]:
%timeit -n 10 a = 2
## 逐層＋1的時間
for i in Z:
    for j in i:
        for k in j:
            i = i + 1 

52.6 ns ± 15.9 ns per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [5]:
%timeit -n 10 a = 2
## 攤平後再迭代
for i in Z.flat:
    i = i+1

52.1 ns ± 20.7 ns per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [6]:
%timeit -n 10 a = 2
## 正確的用法會建議改成使用 np.nditer 迭代物件，這樣才可以享有向量運算的特性。
for i in np.nditer(Z):
    i = i+1

54.2 ns ± 27.4 ns per loop (mean ± std. dev. of 7 runs, 10 loops each)


### 2. 如何從一個陣列中，找出出現頻率最高的數值與位置？


In [9]:

Z = np.random.randint(0,10,50)
print(Z)


[0 0 1 7 0 9 1 7 2 4 0 8 2 7 6 3 8 2 0 9 1 1 3 4 1 3 8 2 7 4 5 4 2 0 8 0 8
 2 0 6 0 3 2 5 8 8 8 8 5 9]


In [10]:
rint = (np.bincount(Z).argmax())
rint

0

In [11]:
np.where(Z == rint)[0]

array([ 0,  1,  4, 10, 18, 33, 35, 38, 40])

### 3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


In [17]:
a = np.random.randint(10, size=6) 

print(a.tolist())
print(list(a))


b = np.random.randint(10, size=(3,4)) 

print(b.tolist())
print(list(b))


c = np.random.randint(10, size=(2,3,2)) 

print(c.tolist())
print(list(c))


[4, 3, 5, 8, 2, 2]
[4, 3, 5, 8, 2, 2]
[[2, 0, 1, 0], [5, 0, 5, 8], [1, 6, 0, 1]]
[array([2, 0, 1, 0]), array([5, 0, 5, 8]), array([1, 6, 0, 1])]
[[[7, 1], [7, 7], [1, 6]], [[5, 7], [5, 8], [2, 4]]]
[array([[7, 1],
       [7, 7],
       [1, 6]]), array([[5, 7],
       [5, 8],
       [2, 4]])]


In [18]:
## 進階版

def tolist(iterable):
    if type(iterable) != np.ndarray:
        return iterable
    return [tolist(obj) for obj in iterable]

print(tolist(a))
print(tolist(b))
print(tolist(c))

[4, 3, 5, 8, 2, 2]
[[2, 0, 1, 0], [5, 0, 5, 8], [1, 6, 0, 1]]
[[[7, 1], [7, 7], [1, 6]], [[5, 7], [5, 8], [2, 4]]]


作業目標<br>
活用矩陣運算，實做線性代數<br>
作業重點<br>
線性代數公式應用<br>
矩陣相乘維度需要對好，例如:2X3矩陣乘上3X5矩陣得到2X5矩陣

### 1. 運用上列array計算反矩陣，乘上原矩陣，並觀察是否為單位矩陣?

In [19]:
#是，雖然算出來沒有完全等於[[1,0],[0,1]]，因為反矩陣計算浮點數的關係所以不會完全等於
array1 = np.array([[10, 8], [3, 5]])
array1_inv = np.linalg.inv(array1)
np.dot(array1_inv,array1)

array([[1., 0.],
       [0., 1.]])

### 2. 運用上列array計算特徵值、特徵向量?

In [20]:
w, v = np.linalg.eig(array1)
print("eigenvalues ",w)
print("eigenvactors ",v)

eigenvalues  [13.  2.]
eigenvactors  [[ 0.93632918 -0.70710678]
 [ 0.35112344  0.70710678]]


### 3. 運用上列array計算SVD?

In [21]:
np.linalg.svd(array1)

(array([[-0.91663818, -0.39971796],
        [-0.39971796,  0.91663818]]),
 array([13.94721714,  1.86417116]),
 array([[-0.74319741, -0.6690722 ],
        [-0.6690722 ,  0.74319741]]))